<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>FsUnit.Xunit</AssemblyName>
    <PackageId>FsUnit.xUnit</PackageId>
    <Description>FsUnit is a set of extensions that add special testing syntax to xUnit.</Description>
    <PackageTags>F# fsharp xUnit FsUnit</PackageTags>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition="($(DesignTimeBuild) == true)">
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="..\Common.fs">
      <Link>Common.fs</Link>
    </Compile>
    <Compile Include="CustomMatchers.fs" />
    <Compile Include="FsUnit.fs" />
    <Compile Include="FsUnitTyped.fs" />
    <None Include="../../docs/img/logo.png" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="NHamcrest" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
