<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>FsUnit.NUnit</AssemblyName>
    <PackageId>FsUnit</PackageId>
    <Description>FsUnit is a set of extensions that add special testing syntax to NUnit.</Description>
    <PackageTags>F# fsharp NUnit FsUnit</PackageTags>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="($(DesignTimeBuild) == true)">
    <DisableImplicitFrameworkReferences>false</DisableImplicitFrameworkReferences>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="..\Common.fs">
      <Link>Common.fs</Link>
    </Compile>
    <Compile Include="CustomConstraints.fs" />
    <Compile Include="Equality.fs" />
    <Compile Include="FsUnit.fs" />
    <Compile Include="FsUnitTyped.fs" />
    <Compile Include="GenericAssert.fs" />
    <None Include="../../docs/img/logo.png" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="NUnit" />
  </ItemGroup>
</Project>