// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsUnit.MsTest")>]
[<assembly: AssemblyProductAttribute("FsUnit")>]
[<assembly: AssemblyDescriptionAttribute("FsUnit is a set of libraries that makes unit-testing with F# more enjoyable.")>]
[<assembly: AssemblyVersionAttribute("6.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("6.0.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsUnit.MsTest"
    let [<Literal>] AssemblyProduct = "FsUnit"
    let [<Literal>] AssemblyDescription = "FsUnit is a set of libraries that makes unit-testing with F# more enjoyable."
    let [<Literal>] AssemblyVersion = "6.0.0.0"
    let [<Literal>] AssemblyFileVersion = "6.0.0.0"
