// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsUnit.MbUnit")>]
[<assembly: AssemblyProductAttribute("FsUnit")>]
[<assembly: AssemblyDescriptionAttribute("FsUnit is a set of libraries that makes unit-testing with F# more enjoyable.")>]
[<assembly: AssemblyVersionAttribute("2.3.2")>]
[<assembly: AssemblyFileVersionAttribute("2.3.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsUnit.MbUnit"
    let [<Literal>] AssemblyProduct = "FsUnit"
    let [<Literal>] AssemblyDescription = "FsUnit is a set of libraries that makes unit-testing with F# more enjoyable."
    let [<Literal>] AssemblyVersion = "2.3.2"
    let [<Literal>] AssemblyFileVersion = "2.3.2"
